# Generated by Django 3.2.12 on 2022-10-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('Account_number', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('password_type', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
